using PendleCodeMonkey.Z80EmulatorLib.Enumerations;
using System.Collections.Generic;

namespace PendleCodeMonkey.Z80EmulatorLib
{
	/// <summary>
	/// Implementation of the <see cref="InstructionTables"/> static class.
	/// </summary>
	internal static class InstructionTables
	{
		/// <summary>
		/// Dictionary of unprefixed instructions.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> Unprefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x00, new InstructionInfo("NOP", OpHandlerID.NOP, AddrMode.Implied, AddrMode.Implied) },
			{ 0x01, new InstructionInfo("LD BC,nn", OpHandlerID.LDRegisterPair, AddrMode.ExtendedImmediate, AddrMode.Register) },
			{ 0x02, new InstructionInfo("LD (BC),A", OpHandlerID.LDRegisterPairAcc, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x03, new InstructionInfo("INC BC", OpHandlerID.INCRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x04, new InstructionInfo("INC B", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x05, new InstructionInfo("DEC B", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x06, new InstructionInfo("LD B,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x07, new InstructionInfo("RLCA", OpHandlerID.RLCA, AddrMode.Implied, AddrMode.Implied) },
			{ 0x08, new InstructionInfo("EX AF,AF'", OpHandlerID.EXAF, AddrMode.Implied, AddrMode.Implied) },
			{ 0x09, new InstructionInfo("ADD HL,BC", OpHandlerID.ADDHLRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x0A, new InstructionInfo("LD A,(BC)", OpHandlerID.LDAccRegisterPair, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x0B, new InstructionInfo("DEC BC", OpHandlerID.DECRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x0C, new InstructionInfo("INC C", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0D, new InstructionInfo("DEC C", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0E, new InstructionInfo("LD C,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x0F, new InstructionInfo("RRCA", OpHandlerID.RRCA, AddrMode.Implied, AddrMode.Implied) },
			{ 0x10, new InstructionInfo("DJNZ e", OpHandlerID.DJNZ, AddrMode.Relative, AddrMode.Implied) },
			{ 0x11, new InstructionInfo("LD DE,nn", OpHandlerID.LDRegisterPair, AddrMode.ExtendedImmediate, AddrMode.Register) },
			{ 0x12, new InstructionInfo("LD (DE),A", OpHandlerID.LDRegisterPairAcc, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x13, new InstructionInfo("INC DE", OpHandlerID.INCRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x14, new InstructionInfo("INC D", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x15, new InstructionInfo("DEC D", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x16, new InstructionInfo("LD D,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x17, new InstructionInfo("RLA", OpHandlerID.RLA, AddrMode.Implied, AddrMode.Implied) },
			{ 0x18, new InstructionInfo("JR e", OpHandlerID.JR, AddrMode.Relative, AddrMode.Implied) },
			{ 0x19, new InstructionInfo("ADD HL,DE", OpHandlerID.ADDHLRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x1A, new InstructionInfo("LD A,(DE)", OpHandlerID.LDAccRegisterPair, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x1B, new InstructionInfo("DEC DE", OpHandlerID.DECRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x1C, new InstructionInfo("INC E", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1D, new InstructionInfo("DEC E", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1E, new InstructionInfo("LD E,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x1F, new InstructionInfo("RRA", OpHandlerID.RRA, AddrMode.Implied, AddrMode.Implied) },
			{ 0x20, new InstructionInfo("JR NZ,e", OpHandlerID.JRCondition, AddrMode.Relative, AddrMode.Implied) },
			{ 0x21, new InstructionInfo("LD HL,nn", OpHandlerID.LDRegisterPair, AddrMode.ExtendedImmediate, AddrMode.Register) },
			{ 0x22, new InstructionInfo("LD (nn),HL", OpHandlerID.LDAddressHL, AddrMode.Register, AddrMode.ExtendedImmediate) },
			{ 0x23, new InstructionInfo("INC HL", OpHandlerID.INCRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x24, new InstructionInfo("INC H", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x25, new InstructionInfo("DEC H", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x26, new InstructionInfo("LD H,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x27, new InstructionInfo("DAA", OpHandlerID.DAA, AddrMode.Implied, AddrMode.Implied) },
			{ 0x28, new InstructionInfo("JR Z,e", OpHandlerID.JRCondition, AddrMode.Relative, AddrMode.Implied) },
			{ 0x29, new InstructionInfo("ADD HL,HL", OpHandlerID.ADDHLRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x2A, new InstructionInfo("LD HL,(nn)", OpHandlerID.LDHLAddress, AddrMode.ExtendedImmediate, AddrMode.Register) },
			{ 0x2B, new InstructionInfo("DEC HL", OpHandlerID.DECRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x2C, new InstructionInfo("INC L", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2D, new InstructionInfo("DEC L", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2E, new InstructionInfo("LD L,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x2F, new InstructionInfo("CPL", OpHandlerID.CPL, AddrMode.Implied, AddrMode.Implied) },
			{ 0x30, new InstructionInfo("JR NC,e", OpHandlerID.JRCondition, AddrMode.Relative, AddrMode.Implied) },
			{ 0x31, new InstructionInfo("LD SP,nn", OpHandlerID.LDRegisterPair, AddrMode.ExtendedImmediate, AddrMode.Register) },
			{ 0x32, new InstructionInfo("LD (nn),A", OpHandlerID.LDAddressAcc, AddrMode.Register, AddrMode.ExtendedImmediate) },
			{ 0x33, new InstructionInfo("INC SP", OpHandlerID.INCRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x34, new InstructionInfo("INC (HL)", OpHandlerID.INCHLIndirect, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x35, new InstructionInfo("DEC (HL)", OpHandlerID.DECHLIndirect, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x36, new InstructionInfo("LD (HL),n", OpHandlerID.LDHLIndirectImm, AddrMode.Immediate, AddrMode.Implied) },
			{ 0x37, new InstructionInfo("SCF", OpHandlerID.SCF, AddrMode.Implied, AddrMode.Implied) },
			{ 0x38, new InstructionInfo("JR C,e", OpHandlerID.JRCondition, AddrMode.Relative, AddrMode.Implied) },
			{ 0x39, new InstructionInfo("ADD HL,SP", OpHandlerID.ADDHLRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x3A, new InstructionInfo("LD A,(nn)", OpHandlerID.LDAccAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x3B, new InstructionInfo("DEC SP", OpHandlerID.DECRegisterPair, AddrMode.Implied, AddrMode.Register) },
			{ 0x3C, new InstructionInfo("INC A", OpHandlerID.INCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3D, new InstructionInfo("DEC A", OpHandlerID.DECRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3E, new InstructionInfo("LD A,n", OpHandlerID.LDRegister, AddrMode.Immediate, AddrMode.Register) },
			{ 0x3F, new InstructionInfo("CCF", OpHandlerID.CCF, AddrMode.Implied, AddrMode.Implied) },
			{ 0x40, new InstructionInfo("LD B,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x41, new InstructionInfo("LD B,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x42, new InstructionInfo("LD B,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x43, new InstructionInfo("LD B,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x44, new InstructionInfo("LD B,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x45, new InstructionInfo("LD B,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x46, new InstructionInfo("LD B,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x47, new InstructionInfo("LD B,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x48, new InstructionInfo("LD C,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x49, new InstructionInfo("LD C,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x4A, new InstructionInfo("LD C,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x4B, new InstructionInfo("LD C,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x4C, new InstructionInfo("LD C,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x4D, new InstructionInfo("LD C,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x4E, new InstructionInfo("LD C,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x4F, new InstructionInfo("LD C,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x50, new InstructionInfo("LD D,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x51, new InstructionInfo("LD D,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x52, new InstructionInfo("LD D,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x53, new InstructionInfo("LD D,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x54, new InstructionInfo("LD D,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x55, new InstructionInfo("LD D,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x56, new InstructionInfo("LD D,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x57, new InstructionInfo("LD D,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x58, new InstructionInfo("LD E,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x59, new InstructionInfo("LD E,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x5A, new InstructionInfo("LD E,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x5B, new InstructionInfo("LD E,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x5C, new InstructionInfo("LD E,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x5D, new InstructionInfo("LD E,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x5E, new InstructionInfo("LD E,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x5F, new InstructionInfo("LD E,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x60, new InstructionInfo("LD H,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x61, new InstructionInfo("LD H,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x62, new InstructionInfo("LD H,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x63, new InstructionInfo("LD H,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x64, new InstructionInfo("LD H,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x65, new InstructionInfo("LD H,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x66, new InstructionInfo("LD H,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x67, new InstructionInfo("LD H,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x68, new InstructionInfo("LD L,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x69, new InstructionInfo("LD L,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x6A, new InstructionInfo("LD L,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x6B, new InstructionInfo("LD L,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x6C, new InstructionInfo("LD L,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x6D, new InstructionInfo("LD L,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x6E, new InstructionInfo("LD L,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x6F, new InstructionInfo("LD L,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x70, new InstructionInfo("LD (HL),B", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x71, new InstructionInfo("LD (HL),C", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x72, new InstructionInfo("LD (HL),D", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x73, new InstructionInfo("LD (HL),E", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x74, new InstructionInfo("LD (HL),H", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x75, new InstructionInfo("LD (HL),L", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x76, new InstructionInfo("HALT", OpHandlerID.HALT, AddrMode.Implied, AddrMode.Implied) },
			{ 0x77, new InstructionInfo("LD (HL),A", OpHandlerID.LDHLRegister, AddrMode.Register, AddrMode.RegisterIndirect) },
			{ 0x78, new InstructionInfo("LD A,B", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x79, new InstructionInfo("LD A,C", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x7A, new InstructionInfo("LD A,D", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x7B, new InstructionInfo("LD A,E", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x7C, new InstructionInfo("LD A,H", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x7D, new InstructionInfo("LD A,L", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x7E, new InstructionInfo("LD A,(HL)", OpHandlerID.LDRegisterHL, AddrMode.RegisterIndirect, AddrMode.Register) },
			{ 0x7F, new InstructionInfo("LD A,A", OpHandlerID.LDRegister, AddrMode.Register, AddrMode.Register) },
			{ 0x80, new InstructionInfo("ADD A,B", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x81, new InstructionInfo("ADD A,C", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x82, new InstructionInfo("ADD A,D", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x83, new InstructionInfo("ADD A,E", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x84, new InstructionInfo("ADD A,H", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x85, new InstructionInfo("ADD A,L", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x86, new InstructionInfo("ADD A,(HL)", OpHandlerID.ADDAccHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x87, new InstructionInfo("ADD A,A", OpHandlerID.ADDAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x88, new InstructionInfo("ADC A,B", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x89, new InstructionInfo("ADC A,C", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x8A, new InstructionInfo("ADC A,D", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x8B, new InstructionInfo("ADC A,E", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x8C, new InstructionInfo("ADC A,H", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x8D, new InstructionInfo("ADC A,L", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x8E, new InstructionInfo("ADC A,(HL)", OpHandlerID.ADCAccHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x8F, new InstructionInfo("ADC A,A", OpHandlerID.ADCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x90, new InstructionInfo("SUB B", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x91, new InstructionInfo("SUB C", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x92, new InstructionInfo("SUB D", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x93, new InstructionInfo("SUB E", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x94, new InstructionInfo("SUB H", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x95, new InstructionInfo("SUB L", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x96, new InstructionInfo("SUB (HL)", OpHandlerID.SUBAccHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x97, new InstructionInfo("SUB A", OpHandlerID.SUBAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x98, new InstructionInfo("SBC A,B", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x99, new InstructionInfo("SBC A,C", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x9A, new InstructionInfo("SBC A,D", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x9B, new InstructionInfo("SBC A,E", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x9C, new InstructionInfo("SBC A,H", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x9D, new InstructionInfo("SBC A,L", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0x9E, new InstructionInfo("SBC A,(HL)", OpHandlerID.SBCAccHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0x9F, new InstructionInfo("SBC A,A", OpHandlerID.SBCAccRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA0, new InstructionInfo("AND B", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA1, new InstructionInfo("AND C", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA2, new InstructionInfo("AND D", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA3, new InstructionInfo("AND E", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA4, new InstructionInfo("AND H", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA5, new InstructionInfo("AND L", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA6, new InstructionInfo("AND (HL)", OpHandlerID.ANDHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xA7, new InstructionInfo("AND A", OpHandlerID.ANDRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA8, new InstructionInfo("XOR B", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xA9, new InstructionInfo("XOR C", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xAA, new InstructionInfo("XOR D", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xAB, new InstructionInfo("XOR E", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xAC, new InstructionInfo("XOR H", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xAD, new InstructionInfo("XOR L", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xAE, new InstructionInfo("XOR (HL)", OpHandlerID.XORHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xAF, new InstructionInfo("XOR A", OpHandlerID.XORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB0, new InstructionInfo("OR B", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB1, new InstructionInfo("OR C", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB2, new InstructionInfo("OR D", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB3, new InstructionInfo("OR E", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB4, new InstructionInfo("OR H", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB5, new InstructionInfo("OR L", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB6, new InstructionInfo("OR (HL)", OpHandlerID.ORHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xB7, new InstructionInfo("OR A", OpHandlerID.ORRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB8, new InstructionInfo("CP B", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xB9, new InstructionInfo("CP C", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xBA, new InstructionInfo("CP D", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xBB, new InstructionInfo("CP E", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xBC, new InstructionInfo("CP H", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xBD, new InstructionInfo("CP L", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xBE, new InstructionInfo("CP (HL)", OpHandlerID.CPHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xBF, new InstructionInfo("CP A", OpHandlerID.CPRegister, AddrMode.Register, AddrMode.Implied) },
			{ 0xC0, new InstructionInfo("RET NZ", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC1, new InstructionInfo("POP BC", OpHandlerID.POPRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC2, new InstructionInfo("JP NZ,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xC3, new InstructionInfo("JP nn", OpHandlerID.JP, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xC4, new InstructionInfo("CALL NZ,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xC5, new InstructionInfo("PUSH BC", OpHandlerID.PUSHRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC6, new InstructionInfo("ADD A,n", OpHandlerID.ADDAccRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xC7, new InstructionInfo("RST &00", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC8, new InstructionInfo("RET Z", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC9, new InstructionInfo("RET", OpHandlerID.RET, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCA, new InstructionInfo("JP Z,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
// CB used for prefix
			{ 0xCC, new InstructionInfo("CALL Z,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xCD, new InstructionInfo("CALL nn", OpHandlerID.CALL, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xCE, new InstructionInfo("ADC A,n", OpHandlerID.ADCAccRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xCF, new InstructionInfo("RST &08", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD0, new InstructionInfo("RET NC", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD1, new InstructionInfo("POP DE", OpHandlerID.POPRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD2, new InstructionInfo("JP NC,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xD3, new InstructionInfo("OUT (n),A", OpHandlerID.OUTAcc, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xD4, new InstructionInfo("CALL NC,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xD5, new InstructionInfo("PUSH DE", OpHandlerID.PUSHRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD6, new InstructionInfo("SUB n", OpHandlerID.SUBAccRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xD7, new InstructionInfo("RST &10", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD8, new InstructionInfo("RET C", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD9, new InstructionInfo("EXX", OpHandlerID.EXX, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDA, new InstructionInfo("JP C,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xDB, new InstructionInfo("IN A,(n)", OpHandlerID.INAcc, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xDC, new InstructionInfo("CALL C,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
// DD used for prefix
			{ 0xDE, new InstructionInfo("SBC A,n", OpHandlerID.SBCAccRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xDF, new InstructionInfo("RST &18", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE0, new InstructionInfo("RET PO", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE1, new InstructionInfo("POP HL", OpHandlerID.POPRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE2, new InstructionInfo("JP PO,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xE3, new InstructionInfo("EX (SP),HL", OpHandlerID.EXSPHL, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE4, new InstructionInfo("CALL PO,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xE5, new InstructionInfo("PUSH HL", OpHandlerID.PUSHRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE6, new InstructionInfo("AND n", OpHandlerID.ANDRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xE7, new InstructionInfo("RST &20", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE8, new InstructionInfo("RET PE", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE9, new InstructionInfo("JP (HL)", OpHandlerID.JPHL, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xEA, new InstructionInfo("JP PE,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xEB, new InstructionInfo("EX DE,HL", OpHandlerID.EXDEHL, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEC, new InstructionInfo("CALL PE,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
// ED used for prefix
			{ 0xEE, new InstructionInfo("XOR n", OpHandlerID.XORRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xEF, new InstructionInfo("RST &28", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF0, new InstructionInfo("RET P", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF1, new InstructionInfo("POP AF", OpHandlerID.POPRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF2, new InstructionInfo("JP P,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xF3, new InstructionInfo("DI", OpHandlerID.DI, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF4, new InstructionInfo("CALL P,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xF5, new InstructionInfo("PUSH AF", OpHandlerID.PUSHRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF6, new InstructionInfo("OR n", OpHandlerID.ORRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xF7, new InstructionInfo("RST &30", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF8, new InstructionInfo("RET M", OpHandlerID.RETCondition, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF9, new InstructionInfo("LD SP,HL", OpHandlerID.LDSPHL, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFA, new InstructionInfo("JP M,nn", OpHandlerID.JPCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xFB, new InstructionInfo("EI", OpHandlerID.EI, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFC, new InstructionInfo("CALL M,nn", OpHandlerID.CALLCondition, AddrMode.ExtendedImmediate, AddrMode.Implied) },
// FD used for prefix
			{ 0xFE, new InstructionInfo("CP n", OpHandlerID.CPRegister, AddrMode.Immediate, AddrMode.Implied) },
			{ 0xFF, new InstructionInfo("RST &38", OpHandlerID.RST, AddrMode.Implied, AddrMode.Implied) }
		};

		/// <summary>
		/// Dictionary of instructions that have a 0xCB byte prefix.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> CBPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x00, new InstructionInfo("RLC B", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x01, new InstructionInfo("RLC C", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x02, new InstructionInfo("RLC D", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x03, new InstructionInfo("RLC E", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x04, new InstructionInfo("RLC H", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x05, new InstructionInfo("RLC L", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x06, new InstructionInfo("RLC (HL)", OpHandlerID.RLCHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x07, new InstructionInfo("RLC A", OpHandlerID.RLCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x08, new InstructionInfo("RRC B", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x09, new InstructionInfo("RRC C", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0A, new InstructionInfo("RRC D", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0B, new InstructionInfo("RRC E", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0C, new InstructionInfo("RRC H", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0D, new InstructionInfo("RRC L", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x0E, new InstructionInfo("RRC (HL)", OpHandlerID.RRCHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x0F, new InstructionInfo("RRC A", OpHandlerID.RRCRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x10, new InstructionInfo("RL B", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x11, new InstructionInfo("RL C", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x12, new InstructionInfo("RL D", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x13, new InstructionInfo("RL E", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x14, new InstructionInfo("RL H", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x15, new InstructionInfo("RL L", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x16, new InstructionInfo("RL (HL)", OpHandlerID.RLHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x17, new InstructionInfo("RL A", OpHandlerID.RLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x18, new InstructionInfo("RR B", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x19, new InstructionInfo("RR C", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1A, new InstructionInfo("RR D", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1B, new InstructionInfo("RR E", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1C, new InstructionInfo("RR H", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1D, new InstructionInfo("RR L", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x1E, new InstructionInfo("RR (HL)", OpHandlerID.RRHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x1F, new InstructionInfo("RR A", OpHandlerID.RRRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x20, new InstructionInfo("SLA B", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x21, new InstructionInfo("SLA C", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x22, new InstructionInfo("SLA D", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x23, new InstructionInfo("SLA E", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x24, new InstructionInfo("SLA H", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x25, new InstructionInfo("SLA L", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x26, new InstructionInfo("SLA (HL)", OpHandlerID.SLAHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x27, new InstructionInfo("SLA A", OpHandlerID.SLARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x28, new InstructionInfo("SRA B", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x29, new InstructionInfo("SRA C", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2A, new InstructionInfo("SRA D", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2B, new InstructionInfo("SRA E", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2C, new InstructionInfo("SRA H", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2D, new InstructionInfo("SRA L", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x2E, new InstructionInfo("SRA (HL)", OpHandlerID.SRAHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x2F, new InstructionInfo("SRA A", OpHandlerID.SRARegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x38, new InstructionInfo("SRL B", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x39, new InstructionInfo("SRL C", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3A, new InstructionInfo("SRL D", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3B, new InstructionInfo("SRL E", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3C, new InstructionInfo("SRL H", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3D, new InstructionInfo("SRL L", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x3E, new InstructionInfo("SRL (HL)", OpHandlerID.SRLHLIndirect, AddrMode.Implied, AddrMode.RegisterIndirect) },
			{ 0x3F, new InstructionInfo("SRL A", OpHandlerID.SRLRegister, AddrMode.Implied, AddrMode.Register) },
			{ 0x40, new InstructionInfo("BIT 0,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x41, new InstructionInfo("BIT 0,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x42, new InstructionInfo("BIT 0,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x43, new InstructionInfo("BIT 0,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x44, new InstructionInfo("BIT 0,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x45, new InstructionInfo("BIT 0,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x46, new InstructionInfo("BIT 0,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x47, new InstructionInfo("BIT 0,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x48, new InstructionInfo("BIT 1,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x49, new InstructionInfo("BIT 1,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4A, new InstructionInfo("BIT 1,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4B, new InstructionInfo("BIT 1,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4C, new InstructionInfo("BIT 1,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4D, new InstructionInfo("BIT 1,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4E, new InstructionInfo("BIT 1,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4F, new InstructionInfo("BIT 1,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x50, new InstructionInfo("BIT 2,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x51, new InstructionInfo("BIT 2,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x52, new InstructionInfo("BIT 2,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x53, new InstructionInfo("BIT 2,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x54, new InstructionInfo("BIT 2,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x55, new InstructionInfo("BIT 2,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x56, new InstructionInfo("BIT 2,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x57, new InstructionInfo("BIT 2,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x58, new InstructionInfo("BIT 3,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x59, new InstructionInfo("BIT 3,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5A, new InstructionInfo("BIT 3,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5B, new InstructionInfo("BIT 3,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5C, new InstructionInfo("BIT 3,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5D, new InstructionInfo("BIT 3,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5E, new InstructionInfo("BIT 3,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5F, new InstructionInfo("BIT 3,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x60, new InstructionInfo("BIT 4,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x61, new InstructionInfo("BIT 4,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x62, new InstructionInfo("BIT 4,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x63, new InstructionInfo("BIT 4,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x64, new InstructionInfo("BIT 4,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x65, new InstructionInfo("BIT 4,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x66, new InstructionInfo("BIT 4,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x67, new InstructionInfo("BIT 4,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x68, new InstructionInfo("BIT 5,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x69, new InstructionInfo("BIT 5,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6A, new InstructionInfo("BIT 5,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6B, new InstructionInfo("BIT 5,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6C, new InstructionInfo("BIT 5,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6D, new InstructionInfo("BIT 5,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6E, new InstructionInfo("BIT 5,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6F, new InstructionInfo("BIT 5,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x70, new InstructionInfo("BIT 6,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x71, new InstructionInfo("BIT 6,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x72, new InstructionInfo("BIT 6,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x73, new InstructionInfo("BIT 6,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x74, new InstructionInfo("BIT 6,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x75, new InstructionInfo("BIT 6,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x76, new InstructionInfo("BIT 6,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x77, new InstructionInfo("BIT 6,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x78, new InstructionInfo("BIT 7,B", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x79, new InstructionInfo("BIT 7,C", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7A, new InstructionInfo("BIT 7,D", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7B, new InstructionInfo("BIT 7,E", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7C, new InstructionInfo("BIT 7,H", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7D, new InstructionInfo("BIT 7,L", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7E, new InstructionInfo("BIT 7,(HL)", OpHandlerID.BITHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7F, new InstructionInfo("BIT 7,A", OpHandlerID.BITRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x80, new InstructionInfo("RES 0,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x81, new InstructionInfo("RES 0,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x82, new InstructionInfo("RES 0,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x83, new InstructionInfo("RES 0,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x84, new InstructionInfo("RES 0,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x85, new InstructionInfo("RES 0,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x86, new InstructionInfo("RES 0,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x87, new InstructionInfo("RES 0,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x88, new InstructionInfo("RES 1,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x89, new InstructionInfo("RES 1,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8A, new InstructionInfo("RES 1,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8B, new InstructionInfo("RES 1,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8C, new InstructionInfo("RES 1,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8D, new InstructionInfo("RES 1,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8E, new InstructionInfo("RES 1,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x8F, new InstructionInfo("RES 1,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x90, new InstructionInfo("RES 2,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x91, new InstructionInfo("RES 2,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x92, new InstructionInfo("RES 2,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x93, new InstructionInfo("RES 2,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x94, new InstructionInfo("RES 2,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x95, new InstructionInfo("RES 2,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x96, new InstructionInfo("RES 2,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x97, new InstructionInfo("RES 2,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x98, new InstructionInfo("RES 3,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x99, new InstructionInfo("RES 3,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9A, new InstructionInfo("RES 3,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9B, new InstructionInfo("RES 3,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9C, new InstructionInfo("RES 3,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9D, new InstructionInfo("RES 3,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9E, new InstructionInfo("RES 3,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0x9F, new InstructionInfo("RES 3,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA0, new InstructionInfo("RES 4,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA1, new InstructionInfo("RES 4,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA2, new InstructionInfo("RES 4,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA3, new InstructionInfo("RES 4,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA4, new InstructionInfo("RES 4,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA5, new InstructionInfo("RES 4,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA6, new InstructionInfo("RES 4,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA7, new InstructionInfo("RES 4,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA8, new InstructionInfo("RES 5,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA9, new InstructionInfo("RES 5,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAA, new InstructionInfo("RES 5,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAB, new InstructionInfo("RES 5,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAC, new InstructionInfo("RES 5,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAD, new InstructionInfo("RES 5,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAE, new InstructionInfo("RES 5,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAF, new InstructionInfo("RES 5,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB0, new InstructionInfo("RES 6,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB1, new InstructionInfo("RES 6,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB2, new InstructionInfo("RES 6,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB3, new InstructionInfo("RES 6,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB4, new InstructionInfo("RES 6,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB5, new InstructionInfo("RES 6,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB6, new InstructionInfo("RES 6,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB7, new InstructionInfo("RES 6,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB8, new InstructionInfo("RES 7,B", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB9, new InstructionInfo("RES 7,C", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBA, new InstructionInfo("RES 7,D", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBB, new InstructionInfo("RES 7,E", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBC, new InstructionInfo("RES 7,H", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBD, new InstructionInfo("RES 7,L", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBE, new InstructionInfo("RES 7,(HL)", OpHandlerID.RESHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBF, new InstructionInfo("RES 7,A", OpHandlerID.RESRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC0, new InstructionInfo("SET 0,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC1, new InstructionInfo("SET 0,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC2, new InstructionInfo("SET 0,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC3, new InstructionInfo("SET 0,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC4, new InstructionInfo("SET 0,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC5, new InstructionInfo("SET 0,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC6, new InstructionInfo("SET 0,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC7, new InstructionInfo("SET 0,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC8, new InstructionInfo("SET 1,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xC9, new InstructionInfo("SET 1,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCA, new InstructionInfo("SET 1,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCB, new InstructionInfo("SET 1,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCC, new InstructionInfo("SET 1,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCD, new InstructionInfo("SET 1,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCE, new InstructionInfo("SET 1,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xCF, new InstructionInfo("SET 1,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD0, new InstructionInfo("SET 2,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD1, new InstructionInfo("SET 2,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD2, new InstructionInfo("SET 2,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD3, new InstructionInfo("SET 2,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD4, new InstructionInfo("SET 2,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD5, new InstructionInfo("SET 2,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD6, new InstructionInfo("SET 2,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD7, new InstructionInfo("SET 2,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD8, new InstructionInfo("SET 3,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xD9, new InstructionInfo("SET 3,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDA, new InstructionInfo("SET 3,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDB, new InstructionInfo("SET 3,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDC, new InstructionInfo("SET 3,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDD, new InstructionInfo("SET 3,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDE, new InstructionInfo("SET 3,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xDF, new InstructionInfo("SET 3,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE0, new InstructionInfo("SET 4,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE1, new InstructionInfo("SET 4,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE2, new InstructionInfo("SET 4,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE3, new InstructionInfo("SET 4,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE4, new InstructionInfo("SET 4,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE5, new InstructionInfo("SET 4,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE6, new InstructionInfo("SET 4,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE7, new InstructionInfo("SET 4,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE8, new InstructionInfo("SET 5,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE9, new InstructionInfo("SET 5,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEA, new InstructionInfo("SET 5,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEB, new InstructionInfo("SET 5,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEC, new InstructionInfo("SET 5,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xED, new InstructionInfo("SET 5,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEE, new InstructionInfo("SET 5,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xEF, new InstructionInfo("SET 5,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF0, new InstructionInfo("SET 6,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF1, new InstructionInfo("SET 6,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF2, new InstructionInfo("SET 6,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF3, new InstructionInfo("SET 6,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF4, new InstructionInfo("SET 6,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF5, new InstructionInfo("SET 6,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF6, new InstructionInfo("SET 6,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF7, new InstructionInfo("SET 6,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF8, new InstructionInfo("SET 7,B", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xF9, new InstructionInfo("SET 7,C", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFA, new InstructionInfo("SET 7,D", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFB, new InstructionInfo("SET 7,E", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFC, new InstructionInfo("SET 7,H", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFD, new InstructionInfo("SET 7,L", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFE, new InstructionInfo("SET 7,(HL)", OpHandlerID.SETHLIndirect, AddrMode.Implied, AddrMode.Implied) },
			{ 0xFF, new InstructionInfo("SET 7,A", OpHandlerID.SETRegister, AddrMode.Implied, AddrMode.Implied) }
		};

		/// <summary>
		/// Dictionary of instructions that have a 0xDD byte prefix.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> DDPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x09, new InstructionInfo("ADD IX,BC", OpHandlerID.ADDIXRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x19, new InstructionInfo("ADD IX,DE", OpHandlerID.ADDIXRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x21, new InstructionInfo("LD IX,nn", OpHandlerID.LDIXAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x22, new InstructionInfo("LD (nn),IX", OpHandlerID.LDAddressIndirectIX, AddrMode.Implied, AddrMode.ExtendedImmediate) },
			{ 0x23, new InstructionInfo("INC IX", OpHandlerID.INCIX, AddrMode.Implied, AddrMode.Implied) },
			{ 0x29, new InstructionInfo("ADD IX,IX", OpHandlerID.ADDIXRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x2A, new InstructionInfo("LD IX,(nn)", OpHandlerID.LDIXAddressIndirect, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x2B, new InstructionInfo("DEC IX", OpHandlerID.DECIX, AddrMode.Implied, AddrMode.Implied) },
			{ 0x34, new InstructionInfo("INC (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x35, new InstructionInfo("DEC (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x36, new InstructionInfo("LD (IX+d),n", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Immediate) },
			{ 0x39, new InstructionInfo("ADD IX,SP", OpHandlerID.ADDIXRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x46, new InstructionInfo("LD B,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x4E, new InstructionInfo("LD C,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x56, new InstructionInfo("LD D,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x5E, new InstructionInfo("LD E,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x66, new InstructionInfo("LD H,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x6E, new InstructionInfo("LD L,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x70, new InstructionInfo("LD (IX+d),B", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x71, new InstructionInfo("LD (IX+d),C", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x72, new InstructionInfo("LD (IX+d),D", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x73, new InstructionInfo("LD (IX+d),E", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x74, new InstructionInfo("LD (IX+d),H", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x75, new InstructionInfo("LD (IX+d),L", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x77, new InstructionInfo("LD (IX+d),A", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x7E, new InstructionInfo("LD A,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x86, new InstructionInfo("ADD A,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x8E, new InstructionInfo("ADC A,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x96, new InstructionInfo("SUB (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x9E, new InstructionInfo("SBC A,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xA6, new InstructionInfo("AND (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xAE, new InstructionInfo("XOR (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xB6, new InstructionInfo("OR (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xBE, new InstructionInfo("CP (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xE1, new InstructionInfo("POP IX", OpHandlerID.POPIX, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE3, new InstructionInfo("EX (SP),IX", OpHandlerID.EXSPIX, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE5, new InstructionInfo("PUSH IX", OpHandlerID.PUSHIX, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE9, new InstructionInfo("JP (IX)", OpHandlerID.JPIX, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xF9, new InstructionInfo("LD SP,IX", OpHandlerID.LDSPIX, AddrMode.Implied, AddrMode.Implied) }
		};

		/// <summary>
		/// Dictionary of instructions that are prefixed by 0xDD 0xCB.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> DDCBPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x06, new InstructionInfo("RLC (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x0E, new InstructionInfo("RRC (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x16, new InstructionInfo("RL (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x1E, new InstructionInfo("RR (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x26, new InstructionInfo("SLA (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x2E, new InstructionInfo("SRA (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x3E, new InstructionInfo("SRL (IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x46, new InstructionInfo("BIT 0,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x4E, new InstructionInfo("BIT 1,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x56, new InstructionInfo("BIT 2,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x5E, new InstructionInfo("BIT 3,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x66, new InstructionInfo("BIT 4,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x6E, new InstructionInfo("BIT 5,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x76, new InstructionInfo("BIT 6,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x7E, new InstructionInfo("BIT 7,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x86, new InstructionInfo("RES 0,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x8E, new InstructionInfo("RES 1,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x96, new InstructionInfo("RES 2,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x9E, new InstructionInfo("RES 3,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xA6, new InstructionInfo("RES 4,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xAE, new InstructionInfo("RES 5,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xB6, new InstructionInfo("RES 6,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xBE, new InstructionInfo("RES 7,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xC6, new InstructionInfo("SET 0,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xCE, new InstructionInfo("SET 1,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xD6, new InstructionInfo("SET 2,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xDE, new InstructionInfo("SET 3,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xE6, new InstructionInfo("SET 4,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xEE, new InstructionInfo("SET 5,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xF6, new InstructionInfo("SET 6,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xFE, new InstructionInfo("SET 7,(IX+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) }
		};

		/// <summary>
		/// Dictionary of instructions that have a 0xED byte prefix.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> EDPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x40, new InstructionInfo("IN B,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x41, new InstructionInfo("OUT (C),B", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x42, new InstructionInfo("SBC HL,BC", OpHandlerID.SBCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x43, new InstructionInfo("LD (nn),BC", OpHandlerID.LDAddressRegisterPair, AddrMode.Implied, AddrMode.ExtendedImmediate) },
			{ 0x44, new InstructionInfo("NEG", OpHandlerID.NEG, AddrMode.Implied, AddrMode.Implied) },
			{ 0x45, new InstructionInfo("RETN", OpHandlerID.RETN, AddrMode.Implied, AddrMode.Implied) },
			{ 0x46, new InstructionInfo("IM 0", OpHandlerID.InterruptMode0, AddrMode.Implied, AddrMode.Implied) },
			{ 0x47, new InstructionInfo("LD I,A", OpHandlerID.LDIAcc, AddrMode.Implied, AddrMode.Implied) },
			{ 0x48, new InstructionInfo("IN C,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x49, new InstructionInfo("OUT (C),C", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4A, new InstructionInfo("ADC HL,BC", OpHandlerID.ADCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4B, new InstructionInfo("LD BC,(nn)", OpHandlerID.LDRegisterPairAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x4D, new InstructionInfo("RETI", OpHandlerID.RETI, AddrMode.Implied, AddrMode.Implied) },
			{ 0x4F, new InstructionInfo("LD R,A", OpHandlerID.LDRAcc, AddrMode.Implied, AddrMode.Implied) },
			{ 0x50, new InstructionInfo("IN D,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x51, new InstructionInfo("OUT (C),D", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x52, new InstructionInfo("SBC HL,DE", OpHandlerID.SBCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x53, new InstructionInfo("LD (nn),DE", OpHandlerID.LDAddressRegisterPair,AddrMode.Implied, AddrMode.ExtendedImmediate) },
			{ 0x56, new InstructionInfo("IM 1", OpHandlerID.InterruptMode1, AddrMode.Implied, AddrMode.Implied) },
			{ 0x57, new InstructionInfo("LD A,I", OpHandlerID.LDAccI, AddrMode.Implied, AddrMode.Implied) },
			{ 0x58, new InstructionInfo("IN E,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x59, new InstructionInfo("OUT (C),E", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5A, new InstructionInfo("ADC HL,DE", OpHandlerID.ADCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5B, new InstructionInfo("LD DE,(nn)", OpHandlerID.LDRegisterPairAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x5E, new InstructionInfo("IM 2", OpHandlerID.InterruptMode2, AddrMode.Implied, AddrMode.Implied) },
			{ 0x5F, new InstructionInfo("LD A,R", OpHandlerID.LDAccR, AddrMode.Implied, AddrMode.Implied) },
			{ 0x60, new InstructionInfo("IN H,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x61, new InstructionInfo("OUT (C),H", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x62, new InstructionInfo("SBC HL,HL", OpHandlerID.SBCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x67, new InstructionInfo("RRD", OpHandlerID.RRD, AddrMode.Implied, AddrMode.Implied) },
			{ 0x68, new InstructionInfo("IN L,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x69, new InstructionInfo("OUT (C),L", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6A, new InstructionInfo("ADC HL,HL", OpHandlerID.ADCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x6F, new InstructionInfo("RLD", OpHandlerID.RLD, AddrMode.Implied, AddrMode.Implied) },
			{ 0x72, new InstructionInfo("SBC HL,SP", OpHandlerID.SBCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x73, new InstructionInfo("LD (nn),SP", OpHandlerID.LDAddressRegisterPair, AddrMode.Implied, AddrMode.ExtendedImmediate) },
			{ 0x78, new InstructionInfo("IN A,(C)", OpHandlerID.INRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x79, new InstructionInfo("OUT (C),A", OpHandlerID.OUTRegister, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7A, new InstructionInfo("ADC HL,SP", OpHandlerID.ADCHLRegisterPair, AddrMode.Implied, AddrMode.Implied) },
			{ 0x7B, new InstructionInfo("LD SP,(nn)", OpHandlerID.LDRegisterPairAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0xA0, new InstructionInfo("LDI", OpHandlerID.LDIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA1, new InstructionInfo("CPI", OpHandlerID.CPIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA2, new InstructionInfo("INI", OpHandlerID.INIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA3, new InstructionInfo("OUTI", OpHandlerID.OUTIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA8, new InstructionInfo("LDD", OpHandlerID.LDIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xA9, new InstructionInfo("CPD", OpHandlerID.CPIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAA, new InstructionInfo("IND", OpHandlerID.INIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xAB, new InstructionInfo("OUTD", OpHandlerID.OUTIncDec, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB0, new InstructionInfo("LDIR", OpHandlerID.LDIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB1, new InstructionInfo("CPIR", OpHandlerID.CPIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB2, new InstructionInfo("INIR", OpHandlerID.INIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB3, new InstructionInfo("OTIR", OpHandlerID.OUTIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB8, new InstructionInfo("LDDR", OpHandlerID.LDIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xB9, new InstructionInfo("CPDR", OpHandlerID.CPIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBA, new InstructionInfo("INDR", OpHandlerID.INIncDecRepeat, AddrMode.Implied, AddrMode.Implied) },
			{ 0xBB, new InstructionInfo("OTDR", OpHandlerID.OUTIncDecRepeat, AddrMode.Implied, AddrMode.Implied) }
		};

		/// <summary>
		/// Dictionary of instructions that have a 0xFD byte prefix.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> FDPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x09, new InstructionInfo("ADD IY,BC", OpHandlerID.ADDIYRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x19, new InstructionInfo("ADD IY,DE", OpHandlerID.ADDIYRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x21, new InstructionInfo("LD IY,nn", OpHandlerID.LDIYAddress, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x22, new InstructionInfo("LD (nn),IY", OpHandlerID.LDAddressIndirectIY, AddrMode.Implied, AddrMode.ExtendedImmediate) },
			{ 0x23, new InstructionInfo("INC IY", OpHandlerID.INCIY, AddrMode.Implied, AddrMode.Implied) },
			{ 0x29, new InstructionInfo("ADD IY,IY", OpHandlerID.ADDIYRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x2A, new InstructionInfo("LD IY,(nn)", OpHandlerID.LDIYAddressIndirect, AddrMode.ExtendedImmediate, AddrMode.Implied) },
			{ 0x2B, new InstructionInfo("DEC IY", OpHandlerID.DECIY, AddrMode.Implied, AddrMode.Implied) },
			{ 0x34, new InstructionInfo("INC (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x35, new InstructionInfo("DEC (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x36, new InstructionInfo("LD (IY+d),n", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Immediate) },
			{ 0x39, new InstructionInfo("ADD IY,SP", OpHandlerID.ADDIYRegisterPair, AddrMode.Register, AddrMode.Implied) },
			{ 0x46, new InstructionInfo("LD B,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x4E, new InstructionInfo("LD C,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x56, new InstructionInfo("LD D,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x5E, new InstructionInfo("LD E,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x66, new InstructionInfo("LD H,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x6E, new InstructionInfo("LD L,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x70, new InstructionInfo("LD (IY+d),B", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x71, new InstructionInfo("LD (IY+d),C", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x72, new InstructionInfo("LD (IY+d),D", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x73, new InstructionInfo("LD (IY+d),E", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x74, new InstructionInfo("LD (IY+d),H", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x75, new InstructionInfo("LD (IY+d),L", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x77, new InstructionInfo("LD (IY+d),A", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x7E, new InstructionInfo("LD A,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x86, new InstructionInfo("ADD A,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x8E, new InstructionInfo("ADC A,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x96, new InstructionInfo("SUB (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x9E, new InstructionInfo("SBC A,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xA6, new InstructionInfo("AND (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xAE, new InstructionInfo("XOR (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xB6, new InstructionInfo("OR (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xBE, new InstructionInfo("CP (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xE1, new InstructionInfo("POP IY", OpHandlerID.POPIY, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE3, new InstructionInfo("EX (SP),IY", OpHandlerID.EXSPIY, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE5, new InstructionInfo("PUSH IY", OpHandlerID.PUSHIY, AddrMode.Implied, AddrMode.Implied) },
			{ 0xE9, new InstructionInfo("JP (IY)", OpHandlerID.JPIY, AddrMode.RegisterIndirect, AddrMode.Implied) },
			{ 0xF9, new InstructionInfo("LD SP,IY", OpHandlerID.LDSPIY, AddrMode.Implied, AddrMode.Implied) }
		};

		/// <summary>
		/// Dictionary of instructions that are prefixed by 0xFD 0xCB.
		/// </summary>
		internal static Dictionary<byte, InstructionInfo> FDCBPrefixed_Instructions
		{ get; } = new Dictionary<byte, InstructionInfo>()
		{
			{ 0x06, new InstructionInfo("RLC (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x0E, new InstructionInfo("RRC (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x16, new InstructionInfo("RL (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x1E, new InstructionInfo("RR (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x26, new InstructionInfo("SLA (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x2E, new InstructionInfo("SRA (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x3E, new InstructionInfo("SRL (IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x46, new InstructionInfo("BIT 0,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x4E, new InstructionInfo("BIT 1,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x56, new InstructionInfo("BIT 2,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x5E, new InstructionInfo("BIT 3,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x66, new InstructionInfo("BIT 4,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x6E, new InstructionInfo("BIT 5,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x76, new InstructionInfo("BIT 6,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x7E, new InstructionInfo("BIT 7,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x86, new InstructionInfo("RES 0,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x8E, new InstructionInfo("RES 1,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x96, new InstructionInfo("RES 2,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0x9E, new InstructionInfo("RES 3,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xA6, new InstructionInfo("RES 4,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xAE, new InstructionInfo("RES 5,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xB6, new InstructionInfo("RES 6,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xBE, new InstructionInfo("RES 7,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xC6, new InstructionInfo("SET 0,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xCE, new InstructionInfo("SET 1,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xD6, new InstructionInfo("SET 2,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xDE, new InstructionInfo("SET 3,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xE6, new InstructionInfo("SET 4,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xEE, new InstructionInfo("SET 5,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xF6, new InstructionInfo("SET 6,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) },
			{ 0xFE, new InstructionInfo("SET 7,(IY+d)", OpHandlerID.IXIYIndirect, AddrMode.Relative, AddrMode.Indexed) }
		};
	}
}
